### PR TITLE
Fix infinite loop on clean disconnect.

### PR DESCRIPTION
**Pull request by bdraco**
Should solve https://github.com/upsert/lutron-caseta-pro/issues/50

### CODE REVIEW

**Review by upsert — CHANGES_REQUESTED** [review]
Thanks for tracking this down! It explains some lockups I've had with no logs and no other clues. I had assumed it was related to upgrades but it could have been Lutron running maintenance on the bridge.

There is another write() on [line 251](https://github.com/upsert/lutron-caseta-pro/pull/51/files#diff-ad8b26cbf9d47cbe91047048ff6dba37R251). Should that be drained too?

**Comment by bdraco** [comment]
> Thanks for tracking this down! It explains some lockups I've had with no logs and no other clues. I had assumed it was related to upgrades but it could have been Lutron running maintenance on the bridge.
> 
> There is another write() on [line 251](https://github.com/upsert/lutron-caseta-pro/pull/51/files#diff-ad8b26cbf9d47cbe91047048ff6dba37R251). Should that be drained too?

Yes.  I'll push a change shortly

**Review by upsert — APPROVED** [review]
Tested on ha dev branch and working well after a disconnect and reconnect after more than 60 seconds.

**Comment by cajuncoding** [comment]
Looks like I definitely need to update my version (which is pretty old now I imagine...).

**Pull request merged**
